import { ILevelParams } from "../beatmap"

export const allTargets:ILevelParams = {
	"distribution": 1,
	"duration": 60,
	"hand": "split",
	"rate": 3,
	"rhythm": 3,
	"target0": true,
	"target1": true,
	"target10": true,
	"target11": true,
	"target2": true,
	"target3": true,
	"target4": true,
	"target5": true,
	"target6": true,
	"target7": true,
	"target8": true,
	"target9": true,
	"visDistance": 2,
	"wallLeft": false,
	"wallRight": false,
	"wallTop": false,
	"song": "Floating on Neptune"
}

export const allWalls:ILevelParams = {
	"distribution": 1,
	"duration": 60,
	"hand": "split",
	"rate": 3,
	"rhythm": 3,
	"target0": false,
	"target1": false,
	"target10": false,
	"target11": false,
	"target2": false,
	"target3": false,
	"target4": false,
	"target5": false,
	"target6": false,
	"target7": false,
	"target8": false,
	"target9": false,
	"visDistance": 2,
	"wallLeft": true,
	"wallRight": true,
	"wallTop": true,
	"song": "Floating on Neptune"
}

export const everything:ILevelParams = {
	"distribution": 1,
	"duration": 60,
	"hand": "split",
	"rate": 3,
	"rhythm": 3,
	"target0": true,
	"target1": true,
	"target10": true,
	"target11": true,
	"target2": true,
	"target3": true,
	"target4": true,
	"target5": true,
	"target6": true,
	"target7": true,
	"target8": true,
	"target9": true,
	"visDistance": 2,
	"wallLeft": true,
	"wallRight": true,
	"wallTop": true,
	"song": "Floating on Neptune"
}